-- Exports every art/*.aseprite to assets/<name>.png (horizontal strip, one
-- cell per frame) and writes assets/atlas.js describing frame sizes and tags.
-- atlas.js is a plain script so the game also runs from file:// (no fetch).
--
--   aseprite -b --script-param root=$PWD --script tools/export-art.lua

local root = app.params.root or app.fs.currentPath
local ART = app.fs.joinPath(root, "art")
local OUT = app.fs.joinPath(root, "assets")
app.fs.makeAllDirectories(OUT)

local names = {}
for _, f in ipairs(app.fs.listFiles(ART)) do
  if f:match("%.aseprite$") then names[#names+1] = f:gsub("%.aseprite$", "") end
end
table.sort(names)

local js = {"// Generated by tools/export-art.lua — do not edit by hand.\nwindow.ATLAS = {\n"}
for _, name in ipairs(names) do
  local spr = app.open(app.fs.joinPath(ART, name .. ".aseprite"))
  app.command.ExportSpriteSheet{
    ui = false,
    askOverwrite = false,
    type = SpriteSheetType.HORIZONTAL,
    textureFilename = app.fs.joinPath(OUT, name .. ".png"),
    dataFilename = app.fs.joinPath(OUT, name .. ".json"),
    dataFormat = SpriteSheetDataFormat.JSON_ARRAY,
    borderPadding = 0, shapePadding = 0, innerPadding = 0,
    trim = false,
    openGenerated = false,
  }
  local tags = {}
  for _, t in ipairs(spr.tags) do
    tags[#tags+1] = string.format("%q: [%d, %d]", t.name, t.fromFrame.frameNumber - 1, t.toFrame.frameNumber - 1)
  end
  local ms = {}
  for _, f in ipairs(spr.frames) do ms[#ms+1] = tostring(math.floor(f.duration * 1000 + 0.5)) end
  js[#js+1] = string.format("  %q: { src: %q, w: %d, h: %d, frames: %d, ms: [%s],\n    tags: { %s } },\n",
    name, "assets/" .. name .. ".png", spr.width, spr.height, #spr.frames, table.concat(ms, ","), table.concat(tags, ", "))
  print(string.format("export %-8s %2d frames  %d tags", name, #spr.frames, #spr.tags))
  spr:close()
end
js[#js+1] = "};\n"

local f = io.open(app.fs.joinPath(OUT, "atlas.js"), "w")
f:write(table.concat(js))
f:close()
print("wrote assets/atlas.js")
